### ISSUE TITLE
Error in console on FIM completion (and completion not working)

### ISSUE THREAD

**Issue by shockme** [rjmacarthy/twinny#94]
**Describe the bug**
FIM completion is not working. Chat is working.
I've tried with codellama and deepseek-coder, neither worked for FIM.

After completion is triggered, either automatically or manually an error appears in VSCodium console:
```
Error: Illegal value for `line`
	at g._lineAt (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:1174)
	at Object.lineAt (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:138:95)
	at e.CompletionProvider.getFormattedCompletion (/home/user/.vscode-oss/extensions/rjmacarthy.twinny-3.3.5-universal/out/extension.js:2:95650)
	at e.CompletionProvider.triggerInlineCompletion (/home/user/.vscode-oss/extensions/rjmacarthy.twinny-3.3.5-universal/out/extension.js:2:99554)
	at e.CompletionProvider.handleEndStream (/home/user/.vscode-oss/extensions/rjmacarthy.twinny-3.3.5-universal/out/extension.js:2:95131)
	at onEnd (/home/user/.vscode-oss/extensions/rjmacarthy.twinny-3.3.5-universal/out/extension.js:2:97661)
	at IncomingMessage.<anonymous> (/home/user/.vscode-oss/extensions/rjmacarthy.twinny-3.3.5-universal/out/extension.js:2:111201)
	at Object.onceWrapper (node:events:627:28)
	at IncomingMessage.emit (node:events:525:35)
	at endReadableNT (node:internal/streams/readable:1359:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I can see the API being called in the Ollama logs, but no error appears there.

**Expected behavior**
FIM completion should be working.

**Desktop (please complete the following information):**
 - VSCodium Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-01-19T18:30:44.948Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-92-generic
 - Twinny Version 3.3.5

**Additional context**
```
ollama run codellama:7b-code '<PRE> def compute_gcd(x, y): <SUF>return result <MID>'

  while x != y:
    if x > y:
      x = x - y
    else:
       <EOT>
```

**Comment by rjmacarthy** [comment]
Hi please could you update to version `3.3.12`?

**Comment by shockme** [comment]
FIM completion works in 3.3.12. Thanks!
